### ISSUE TITLE
add @ DNS para acessar sem WWW

### ISSUE THREAD

**Issue by keppelen** [devbeers/devbeers.github.io#14]
www.devbeers.io => OK
[devbeers.io](devbeers.io) => down

**Comment by heitortsergent** [comment]
ué, aqui tá redirecionando para o www @keppelen . Alguém mais pode testar?

**Comment by Lucasosf** [comment]
Pra mim também redireciona para www. O_O

**Comment by keppelen** [comment]
![out](https://cloud.githubusercontent.com/assets/602111/7047712/ad0f12b0-dde4-11e4-8c1e-7fd97d2a2f25.gif)

**Comment by heitortsergent** [comment]
@keppelen haha, o gif foi ótimo. :D

Se esperar mais um tempo, ele não redireciona?

**Comment by keppelen** [comment]
Cara agora ta indo instantâneo, ficava minutos sem fazer o redirect.

**Comment by heitortsergent** [comment]
:+1:
