### ISSUE TITLE
devbeers em Fortaleza - CE

### ISSUE THREAD

**Issue by Viniciuscarvalho** [devbeers/devbeers.github.io#18]
## devbeers em Fortaleza ##

Galera, gostaria de acrescentar mais um evento em Fortaleza e acho que estamos crescendo nesse quesito. Estamos consolidando com mais frequência eventos como, Pylestras, Guru-CE, CocoaHeads, Javou, entre outros eventos de comunidades.
Seria ótimo ver acontecer também o devbeers aqui, e levar todas essas comunidades integradas também para beber uma gelada. 

Fica a pedida de que aconteça edições no nordeste brasileiro, principalmente aqui em Fortaleza.

**Comment by heitortsergent** [comment]
Valeu @Viniciuscarvalho!

Pra ficar registrado aqui também, estamos consolidando o evento em SP, BH e RJ por enquanto, para depois expandir. :)

Com mais alguns :+1: a gente sabe que tem interesse da galera. :dancer:

**Comment by infoslack** [comment]
:+1:

**Comment by Russian60** [comment]
Iraadoo! :+1:

**Comment by cicerohen** [comment]
Show :+1:

**Comment by marcelodeveloper** [comment]
Irado! :+1:

**Comment by espellcaste** [comment]
+1

**Comment by jouderianjr** [comment]
Tô dentro! :)

**Comment by adiusu** [comment]
Simbora.

**Comment by Ziggoto** [comment]
#Partiu

**Comment by Wilmerson** [comment]
#Demorou! Tó dentro!

**Comment by vinimdocarmo** [comment]
:+1:

**Comment by jeffesonmaia** [comment]
Show!

**Comment by dehvmartins** [comment]
Plz.

**Comment by rubenspgcavalcante** [comment]
:+1:

**Comment by jonhnes** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by fernandodev** [comment]
![PLUS ONE](https://lh6.ggpht.com/fHwKNtXNPkYNgcU0JVyRTuXzW37qohUPQmA4eYoWAlWGgfJPflh1gsCJL5k3Olfv86kp=w300)

**Comment by pedroaugusto** [comment]
:+1:

**Comment by cjpatoilo** [comment]
:beers:

**Comment by fabiocerqueira** [comment]
:beers: simbora

**Comment by pedromamede** [comment]
Show!

**Comment by filipebarcos** [comment]
seria foda! :+1:

**Comment by scnfilho** [comment]
Tem que ter! :+1: :beers:

**Comment by luiseugenio** [comment]
+1

**Comment by IanRamosC** [comment]
Foda.

**Comment by vitorcarvalhoml** [comment]
show @Viniciuscarvalho

**Comment by cicerohen** [comment]
o/

**Comment by espellcaste** [comment]
O legal é a criatividade da galera com a criação dos nomes dos eventos.. nunca vi igual! =D o/

**Comment by rebeccapinheiro** [comment]
:+1:

**Comment by felipelmota** [comment]
:+1:
