### ISSUE TITLE
devbeers em Novo Hamburgo/RS

### ISSUE THREAD

**Issue by paulodiovani** [devbeers/devbeers.github.io#21]
Gostaria de trazer o DevBeers para **Novo Hamburgo - RS**

Possuimos uma comunidade crescente na cidade e é nosso interesse que cada vez mais desenvolvedores e empresas participem de  evento assim.

No ano passado organizamos o [Code Beers](http://codebeers.github.io/) (como mencionado no #19) e foi um sucesso. Outros eventos que já organizamos por aqui incluem o [Rails Gilrs NH](http://railsgirls.com/novohamburgo) e os [Meetups Vale dos Desenvolvedores](http://www.meetup.com/Vale-dos-Desenvolvedores). 

Possuímos atualmente, em nossos grupos no Meetup.com, [239 participantes no CodeBeers](http://www.meetup.com/Code-Beers/) e [215 no Vale dos Desenvolvedores](http://www.meetup.com/Vale-dos-Desenvolvedores/).

**Comment by boniattirodrigo** [comment]
Olá Paulo, posso ajudar no desenvolvimento do site do evento, além de divulgar para alguns amigos meus aqui de Sapiranga se for de seu interesse.

**Comment by brunoskonrad** [comment]
Acho mais do que válido trazer esse tipo de evento pra cidade. Como o @paulodiovani comentou, a região tem uma boa quantidade de desenvolvedores e curiosos da área (vide o Rails Girls, que foi um sucesso).

Fui nas edições anteriores e, sucesso. Até descolei um trampo novo! HAHAHA

**Comment by taltk9** [comment]
Esse tipo de evento deve ocorrer em Novo Hamburgo por um simples motivo: a cidade possui empresas de tecnologia e uma universidade sedenta por eventos que tragam a realidade do desenvolvimento no mercado. E como o @brunoskonrad citou no comentário acima, também é a oportunidade de devs se aproximarem de empresas que almejam atuar algum dia.

Apoio totalmente que o DevBeers ocorra em Novo Hamburgo/RS
