### ISSUE TITLE
devbeers em Campinas

### ISSUE THREAD

**Issue by IAMFELIPEMATTOS** [devbeers/devbeers.github.io#22]
Conforme eu conversei com o @obetomuniz, eu gostaria de trazer o devbeers para Campinas.
creio que sera muito interessante um evento desses em nossa região, além do que a comunidade por aqui tem estado muito unida e comprometida.
a mesma vem organizando encontros nos quais acontecem mensalmente que é o meetup de front-end, nodeschool e o ionic campinas.

sendo assim, gostaria de saber como proceder diante dessa iniciativa.

**Comment by obetomuniz** [comment]
@heitortsergent Acho interessante maturar a ideia, de acordo com as propostas que estamos tendo sobre Campinas, o que acha?

**Comment by BielRibeiro** [comment]
Todo apoio em trazer o evento para cá manos.
Estamos organizando o Meetup de front-end todo mês e está bem legal.

@IAMFELIPEMATTOS @obetomuniz estou ae para ajudar no que for preciso.

**Comment by pokemaobr** [comment]
Opa, mais que apoio o evento em Campinas, vale bem a pena a iniciativa por aqui. Podem contar comigo também

**Comment by IAMFELIPEMATTOS** [comment]
cc: @obetomuniz @heitortsergent 

o que rolou?

**Comment by heitortsergent** [comment]
Foi mal @IAMFELIPEMATTOS, não respondi aqui na thread.

A gente tá trabalhando pra estabilizar as coisas em SP, BH e RJ ainda, e garantir que todos os eventos tem uma qualidade boa. Mas já tem algumas empresas interessadas em patrocinar edições em Campinas. Posso te dar um update melhor sobre isso depois que passar o Carnaval?

**Comment by IAMFELIPEMATTOS** [comment]
@heitortsergent sem problemas bro, aguardo seu contato :+1:

**Comment by IAMFELIPEMATTOS** [comment]
cc: @heitortsergent 
Alguma novidade relacionada a realização do evento em Campinas?

**Comment by ThamaraHessel** [comment]
Conversa já esta em andamento =)
