### ISSUE TITLE
devbeers em Campo Grande - MS

### ISSUE THREAD

**Issue by antonielcm** [devbeers/devbeers.github.io#43]
Olá pessoal!

Eu conheço o devbeers já faz um tempinho (infelizmente nunca pude participar 😢) e gostaria de tentar trazê-lo para cá.

Temos uma comunidade bem legal de devs aqui, mas os eventos e meetups estão bem parados. Os maiores que temos aqui são o Agile Trends (que tem uma edição aqui) e um evento chamado [Javaneiros](https://www.javaneiros.com.br/) que inicialmente era um evento de Java mas agora abrange várias tecnologias, tendo esse recebido palestrantes de renome nacional. Existem alguns outros dois ou três eventos voltados para Linux e há pouco tivemos o início de um movimento de UX na cidade.

A ideia de trazer o devbeers pra cá surgiu numa conversa sobre essa falta, e vimos que seria uma boa se conseguissemos, pois a "marca" de vocês é conhecida e atrai tanto quem quer participar quanto quem quer patrocinar.

Eu gostaria de saber se é possível e o que precisamos fazer para termos um devbeers rolando aqui na cidade, estamos dispostos a ir atrás de patrocínio (eu mesmo trabalho em uma empresa que patrocina Agile Trends, Agile Brazil, Scrum Rio, TDC, UX Conf, etc.) e de organizar os meetups caso tenhamos a oportunidade.

Fico no aguardo! 😉

**Comment by heitortsergent** [comment]
Oi @antonielcm!

Obrigado por abrir o issue, a gente sempre gosta de ter novas pessoas e cidades interessadas!

O primeiro passo pra começar a organizar e a gente marcar um Hangouts/Skype rapidinho, pra gente se conhecer um pouco melhor, contar como as coisas funcionam na organização, como o evento começou, etc.

Pode me mandar um email no heitor@devbeers.io pra gente combinar, por favor? 💃

**Comment by antonielcm** [comment]
Vou fazer isso @heitortsergent, obrigado! 😄
